"""empty message

Revision ID: 27b2ac3fa137
Revises: 4540e004c72d
Create Date: 2015-01-18 04:34:15.869376

"""

# revision identifiers, used by Alembic.
revision = '27b2ac3fa137'
down_revision = '4540e004c72d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'session')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('session', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    ### end Alembic commands ###
