"""empty message

Revision ID: 4540e004c72d
Revises: 1e36df75a8b9
Create Date: 2015-01-17 20:51:39.467867

"""

# revision identifiers, used by Alembic.
revision = '4540e004c72d'
down_revision = '1e36df75a8b9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
